### ISSUE TITLE
With Ribbon on, do not separate out wires coming from the same pin

### ISSUE THREAD

**Issue by Gliptal** [TheHerobrine/ElectronicNodes#1]
Also see this [post](https://forums.unrealengine.com/unreal-engine/marketplace/1647213-electronic-nodes-wiring-style-for-blueprint-and-material-editors?p=1660501#post1660501).

Example image:

![image](https://forums.unrealengine.com/filedata/fetch?id=1660502&d=1567600807)

**Comment by TheHerobrine** [comment]
@Gliptal This is now solved and will be release in the next update of the plugin 😉

![image](https://user-images.githubusercontent.com/4563971/65817798-b58dd680-e20b-11e9-8283-b938732093c4.png)
