### ISSUE TITLE
Packaged game issue with the plugin

### ISSUE THREAD

**Issue by theknoppix** [TheHerobrine/ElectronicNodes#14]
Packaged game doesn't start because electronic nodes plugin is not loaded. Didn't have any issue like this on 4.23

Unreal engine version: 4.24. 

**Expected behavior**
Packaged game shouldn't contain any info about electronic nodes editor plugin.

**Log**
```log
LogPluginManager: Error: Unable to load plugin 'ElectronicNodes'. Aborting.
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module RenderCore (30)
LogModuleManager: Shutting down and abandoning module Landscape (28)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (26)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (24)
LogModuleManager: Shutting down and abandoning module D3D11RHI (22)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (20)
LogModuleManager: Shutting down and abandoning module Renderer (18)
LogModuleManager: Shutting down and abandoning module Engine (16)
LogModuleManager: Shutting down and abandoning module CoreUObject (14)
LogModuleManager: Shutting down and abandoning module NetworkFile (12)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (10)
LogModuleManager: Shutting down and abandoning module StreamingFile (8)
LogModuleManager: Shutting down and abandoning module SandboxFile (6)
LogModuleManager: Shutting down and abandoning module PakFile (4)
LogModuleManager: Shutting down and abandoning module RSA (3)
LogExit: Exiting.
Log file closed, 01/01/20 21:52:44
```

**Comment by TheHerobrine** [comment]
@theknoppix Yes, I think it's because I forgot a log on that version... I fixed week two weeks ago (on 22/12), but Epic didn't review it yet (they may be on holiday break).

I'll ping you once it's available!

**Comment by theknoppix** [comment]
Thank you @TheHerobrine . I'm disabling the plugin before packaging for now. Once got used to electronic nodes, it's hard to work without it :)

I'm not sure if you have been able to reproduce, but it you couldn't, i can give more information.

**Comment by theknoppix** [comment]
@TheHerobrine Looks like new version solved the issue? I tried on 32bit package and it works, didn't try 64bit but i don't think it will be different?

**Comment by TheHerobrine** [comment]
@theknoppix Happy to ear that everything works fine, I was about to ask you a bit more context about the issue :D ! If you can confirm me that there's no problem with 64bits package (which shouldn't change anything...), I'll close the issue ;)

**Comment by TheHerobrine** [comment]
Without any response for 3 weeks, I consider this to be solved ;)

**Comment by theknoppix** [comment]
Sorry, completely forgot to report that the issue has been solved with mentioned update.

Thank you.
