### ISSUE TITLE
Drop FPS in Editor

### ISSUE THREAD

**Issue by FlamingFuryVN** [TheHerobrine/ElectronicNodes#15]
**Describe the bug**
In a few times, I got drop FPS when working on the blueprint, it causes slow down everything like adds a node, pan/zoom blueprint, open another blueprint, ... The more blueprint was open, the more FPS will drop. And when it too slow, it causes a crash.
I used the plugin "Electronic Nodes" with plugin "Assist Blueprint". For the first time, I thought the reason is plugin "Assist Blueprint" because it always auto - position when adds nodes and I turn off auto - position, but there aren't better. After that, I try to turn off one of each plugin. When your plugin was turned off ("Assist Blueprint" still on), the editor was smoother.

**Expected behavior**
This issue just happens sometimes, sometimes is fine and some don't. Just like the longer I work on, it will happen. Or I open too much blueprint (like 7-8 blueprint at once). But when I report this issue, I just open 1.

**Screenshots**
https://drive.google.com/open?id=1_wlvh4A2ZUVLL6xF-MbcHD6mHyTUtaU2
https://drive.google.com/open?id=1vEgsMlCTG8Dx2TthQZcKlDwyUKEESX11
https://drive.google.com/open?id=1jG-ZxiqElXgJkxbbYwmblPVBTBaXKzGp
Blueprintue : https://blueprintue.com/blueprint/3etrak3e/

**Environment (please complete the following information):**
 - Unreal Engine version: 4.21
 - Operating System: Window 64bit
 - PC Specs
Mainboard GIGABYTE Z390 AORUS ULTRA LGA1151v2
CPU INTEL Core i7 8700k Coffeelake 3.7GHz
RAM HyperX Predator RGB 2x8Gb 3200MHz
VGA GIGABYTE GeForce RTX™ 2080 SUPER AORUS 8G
SSD WD Black SN750 250G M.2 NVMe PCIe
PSU Corsair RM750 80 Plus GOLD 80 PLUS GOLD
Case Lian Li PC-011 DYNAMIC Black 
Cooling Corsair Hydro Series™ H150i Pro RGB 360mm

**Comment by TheHerobrine** [comment]
@FlamingFuryVN Thank you very much for creating the ticket!

I opened your blueprint (by copy pasting it from blueprintue.com) and I didn't have any problem... Your computer seems a lot more powerful than mine, so I find it confusing :/...

I have a few more questions:

- What is the version of the plugin? You can find it under `Edit/Plugins`
![image](https://user-images.githubusercontent.com/4563971/73301741-a3e92980-4213-11ea-8dc2-bc8eb03709ec.png)
- Is there any special log in the ouput log panel?
![image](https://user-images.githubusercontent.com/4563971/73302105-5ae5a500-4214-11ea-96cb-d673af37f689.png)
- When lagging, if you go to `Edit/Editor Preferences/Plugins/Electronic Nodes Plugin` and master deactivate the plugin, does temporary solve the lags? (In old versions it may be `Wire style: default`)
![image](https://user-images.githubusercontent.com/4563971/73302246-97190580-4214-11ea-9061-f66ad42f0a8c.png)

I know it's not a viable solution for a game, but have you try to use your project under UE4.24? Just to see if the lag still appear.

**Comment by FlamingFuryVN** [comment]
+ What is the version of the plugin?
My version is 1.1, I don't know why my version is lower. Sometimes I got icon "!" and note a new update but it doesn't do anything. Epic Launcher doesn't auto-update? Should I need to manually update it? And how do I do that? I'm confusing about version, at the current project I got 1.1 and I create a new one it got 2.1. 
+ Is there any special log in the output log panel?
I hadn't noted it, but I remember sometime my PC got freeze, output log got a red error. I'll note it in the future when I got it again.
+ Ok, I'll try. I haven't used version 4.24 yet, I only use 4.21; 4.22

**Comment by TheHerobrine** [comment]
@FlamingFuryVN 
- The version of the plugin correspond to updates I made. You can see the change log here: https://github.com/TheHerobrine/ElectronicNodes. There's a pretty big update from 1.x to 2.x so you should definitely try to update it!
I'm not 100% sure Epic does auto-update... Isn't there an update button when you click the little exclamation mark?
- It was just to be sure no error is fire at every tick. You may want to note the error though, it might be helpful.
- Nice! You may get some improvement on blueprints, but from what you said, the main problem may be that you have an old version of the plugin. The 2.x version is more optimized.

**Comment by TheHerobrine** [comment]
I'm closing this, don't hesitate to reopen it if you still have the problem 😉
