### ISSUE TITLE
Can't build Cpp project, when this plugin installed on engine.

### ISSUE THREAD

**Issue by brainode** [TheHerobrine/ElectronicNodes#16]
**Describe the bug**
I have cpp project, in this project Electronic Nodes plugin isn't enabled. When i'm trying to build project, i've got this error:
```
UE_4.24\Engine\Plugins\Marketplace\ElectronicNodes\Source\ElectronicNodes\ElectronicNodes.Build.cs(8,14) : error CS0101: The namespace '<global namespace>' already contains a definition for 'ElectronicNodes'
ERROR: Unable to compile source files.
```

**To Reproduce**
1. Create cpp project with 4.24.2 engine.
2. Install plugin to 4.24.2 engine, so plugin won't be enabled for this project.
3. Try to build cpp project.

**Environment (please complete the following information):**
 - Unreal Engine version: 4.24.2
 - Operating System: Windows 10 x64 Version 1909

**Comment by TheHerobrine** [comment]
Hello @brainode ! Sorry for this weird bug...

- Don't you have Electronic Nodes installed in the engine AND your game (inside the `Plugins` folder?)
- Could you try deleting the `Intermediate` folder and building it again?

Aaaand, I just saw that you closed the issue... Is your problem solved?

**Comment by brainode** [comment]
@TheHerobrine , Hi! Sorry for interrupting! My mistake, have 2 copies. Now all works as expected, i left forlder in engine folder.
Thx for fast replying!
