### ISSUE TITLE
Crash when launching on a Oculus Quest

### ISSUE THREAD

**Issue by ClonedPuppy** [TheHerobrine/ElectronicNodes#18]
**Describe the bug**
I'm not sure if this perhaps is expected behaviour, but thought I'd mention it. When I try to launch a build on a Oculus Quest device (Android / Vulkan) the process crashes once the app is about to start on the headset.

**To Reproduce**
Just Press launch and wait for the build and upload to finish, then once the headset is activated it crashes immediately.

**Expected behavior**
Built app should start, and does so without problem once I disable the plugin from UE4.

**Environment (please complete the following information):**
 - Unreal Engine version: UE 4.24.3
 - Operating System: Windows 10 x64

**Additional context**
A snipet of the last bit of the output log:

`LogPlayLevel:   04-06 18:09:45.059 21385 21402 D UE4     : FAndroidGPUInfo

LogPlayLevel:   04-06 18:09:45.059 21385 21402 D UE4     : AndroidEGL::InitSurface 0, 0

LogPlayLevel:   04-06 18:09:45.059 21385 21402 D UE4     : AndroidEGL::InitSurface, Using width: 2880, height 1600

LogPlayLevel:   04-06 18:09:45.059 21385 21402 D UE4     : [GameActivity] [JAVA] - SetDesiredViewSize width=2880 and height=1600

LogPlayLevel:   04-06 18:09:45.059 21385 21402 D UE4     : AndroidEGL::InitSurface, wnd: 0x7fa6059410, width: 2880, height 1600

LogPlayLevel:   04-06 18:09:45.059 21385 21402 D UE4     : AndroidEGL::CreateEGLSurface(0), eglSurface = eglCreatePbufferSurface(), 8x8

LogPlayLevel:   04-06 18:09:45.059 21385 21402 D UE4     : AndroidEGL::CreateEGLSurface(0), auxSurface = eglCreatePbufferSurface(), 8x8

LogPlayLevel: Error:   04-06 18:09:45.312 21385 21402 D UE4     : LogPluginManager: Error: Unable to load plugin 'ElectronicNodes'. Aborting.

LogPlayLevel:   04-06 18:09:45.344 21385 21402 D UE4     : Assertion failed: false [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Launch/Private/Android/LaunchAndroid.cpp] [Line: 463]

LogPlayLevel:   04-06 18:09:45.344 21385 21402 D UE4     : Engine Preinit Failed

LogPlayLevel:   04-06 18:09:45.344 21385 21402 D UE4     : Assertion failed: false [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Launch/Private/Android/LaunchAndroid.cpp] [Line: 463]

LogPlayLevel:   04-06 18:09:45.344 21385 21402 D UE4     : Engine Preinit Failed

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: === Critical error: ===

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error:

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: Assertion failed: false [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Launch/Private/Android/LaunchAndroid.cpp] [Line: 463]

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: Engine Preinit Failed

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: [Callstack] 0x0000007F824E6C7C libUE4.so(0x0000000004B60C7C)!FDebug::CheckVerifyFailedImpl(char const*, char const*, int, char16_t const*, ...)  []

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: [Callstack] 0x0000007F81D5C338 libUE4.so(0x00000000043D6338)!AndroidMain(android_app*)  []

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: [Callstack] 0x0000007F81D69FCC libUE4.so(0x00000000043E3FCC)!android_main()  []

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: [Callstack] 0x0000007F81D8D95C libUE4.so(0x000000000440795C)![Unknown]()  []

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: [Callstack] 0x0000007FA6723458 libc.so(0x0000000000076458)![Unknown]()  []

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error: [Callstack] 0x0000007FA66CB208 libc.so(0x000000000001E208)![Unknown]()  []

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error:

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error:

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error:

LogPlayLevel: Error:   04-06 18:09:45.345 21385 21402 D UE4     : LogAndroid: Error:

LogPlayLevel:   04-06 18:09:45.365 21385 21402 D UE4     : LogAndroid: FAndroidMisc::RequestExit(1)

LogPlayLevel: Took 0.2768376s to run adb.exe, ExitCode=0

LogPlayLevel: Running: C:\NVPACK\android-sdk-windows\platform-tools\adb.exe -s 1PASH9AAD99114 logcat -d`

**Comment by TheHerobrine** [comment]
Hello @ClonedPuppy ! It appears this kind of bug is due to your project not being a C++ one...

Could you try to create a C++ classe anywhere in your project and then build it to be sure everything is fine?

Source: https://forums.unrealengine.com/community/general-discussion/1727267-logpluginmanager-error-unable-to-load-plugin-runtimetests-aborting-solved

**Comment by ClonedPuppy** [comment]
Hi! Thanks so much for your quick reply, love your plugin. Ok, I will try this, need to do some reading up first as I usually only do vanilla blueprint projects. I will post again once I figure it out. 

Is this "bug" due to being a 3rd party plugin?

**Comment by TheHerobrine** [comment]
I think it's because of how Unreal deal with plugins C++ and Blueprint project, but I can't be sure...

Keep me posted on if the solution works :) !

**Comment by TheHerobrine** [comment]
I'm closing this, if you have any feedback, to hesitate to ping me ;)
