### ISSUE TITLE
Problem with packaged UE4 projects not loading

### ISSUE THREAD

**Issue by x3nn3xy** [TheHerobrine/ElectronicNodes#19]
After packaging a project in the stock version 4.24 of the Unreal Engine, it appears, that I'm somehow unable to start the packaged game. Whenever I try to start it, the windows loading icon pops up for a few seconds, but the game isn't loading at all.
Disabeling the plugin before packaging fixed the problem for me, but you always have to load up the editor twice in order to enable, disable it.

**To Reproduce**

1. Package a project in the development build configuration.
2. After the packaging is done go ahead and try launching the now packaged project using the .exe.
3. You can now see the windows loading icon for a few seconds, but nothing else.

**Expected behavior**
Normaly, the game should launch after executing the .exe.

**Environment (please complete the following information):**
 - Unreal Engine version: 4.24
 - Operating System: Windows 64bits

**Comment by TheHerobrine** [comment]
I never managed to reproduce this... Did you have the last version of the plugin? Was your game C++ based?

cf https://github.com/TheHerobrine/ElectronicNodes/wiki/FAQ#i-cant-package-my-game-with-the-plugin-activated

**Comment by x3nn3xy** [comment]
I used the latest version of the plugin with a blueprint based ue4 project.

**Comment by TheHerobrine** [comment]
@x3nn3xy Ooooh, so you should either
- disable the plugin when compiling
- convert your project to C++ based (it doesn't change anything at all)
   Just create a dummy C++ class and delete it right away. That's all. (sorry for not giving this information earlier 😕...)

**Comment by x3nn3xy** [comment]
No big deal man,

appart from this litte issue, your plugin is really well made.
Thx for sending me a solution.

**Comment by TheHerobrine** [comment]
Thank you very much, it makes me really happy 😄! (And again, so sorry for the late answer...)
