### ISSUE TITLE
Allow exec wires to be aligned left rather than right

### ISSUE THREAD

**Issue by Gliptal** [TheHerobrine/ElectronicNodes#2]
Currently exec nodes wires curve as right as possible, near the receiving node. Would it be possible to align them left, near the outgoing node?

Example image:

![UE4Editor_xkj7BufbTB](https://user-images.githubusercontent.com/3907646/64764196-e0a4d480-d541-11e9-97ba-f070b8fa1cfb.png)

**Comment by Gliptal** [comment]
> @Gliptal Would it solve your situation if there were 4 wire styles like:
> 
> * Simple (aligned left)
> * Simple (aligned right)
> * Complex (aligned left)
> * Complex (aligned right) ?

That would be great yes!

**Comment by TheHerobrine** [comment]
@Gliptal Sorry for the delay 😅... Ok, so there will be even more possibilities :
- Aligned right
![image](https://user-images.githubusercontent.com/4563971/65815273-de9f6e80-e1ed-11e9-8079-5fb11c5e82af.png)
- Aligned left
![image](https://user-images.githubusercontent.com/4563971/65815279-e3fcb900-e1ed-11e9-9393-2a4d6fc3fe6d.png)
- Aligned to nodes
![image](https://user-images.githubusercontent.com/4563971/65815285-eb23c700-e1ed-11e9-9bc1-e018737b0fc1.png)
- Aligned to pins
![image](https://user-images.githubusercontent.com/4563971/65815286-f1b23e80-e1ed-11e9-9303-139dcd646345.png)

This feature will be available on the next release, so I close the ticket, but don't hesitate to add a comment if you have any question/suggestion 😉
