### ISSUE TITLE
Unnecessary #include ".cpp"

### ISSUE THREAD

**Issue by GloryOfNight** [TheHerobrine/ElectronicNodes#20]
Hi! 

Found recently this line in ENAnimGraphConnectionDrawingPolicy.cpp:3
`#include "AnimGraphConnectionDrawingPolicy.cpp"`

Is this necessary to include this .cpp file into other .cpp? In 4.25 I see not so much reasoning for this (no reasons at all to be clear). 
 What was the point doing so? 

Source code of included file:
[Source](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Editor/AnimationBlueprintEditor/Private/AnimGraphConnectionDrawingPolicy.cpp)

**Comment by TheHerobrine** [comment]
@GloryOfNight Ooooh, I'm so sorry, I just discovered your issue right now... I'll check this out but, but I remembered it was for it to work on animation blueprint. I'll keep you posted on ;)

(Thank you very much your investigation !)

**Comment by TheHerobrine** [comment]
@GloryOfNight So for the 4.26 update, I removed this and the whole `ENAnimGraphConnectionDrawingPolicy` files (you were right, it was some code to make it work for previous versions of the engine)
I also removed a bunch of other unnecessary stuff. The 4.26 version will be available in the next days 🙂

Thanks again for the investigation!

**Comment by TheHerobrine** [comment]
@GloryOfNight Ok, so after further investigation, I have to add it back 😅... This include is to make Electronic Nodes works with `AnimationGraphSchema` and `AnimationStateGraphSchema` like this:
![image](https://user-images.githubusercontent.com/4563971/101258528-55ee5d80-3723-11eb-8273-60a3c0955065.png)

It works without this include, but it loses the ability to know what wire is "active" and draw the bubbles on these wires.
I missed this when reviewing the modification for 4.26 since I do not use animations for my game (and it's a bit hidden)

I'm really sorry, but I have to add it back 😅...

**Comment by TheHerobrine** [comment]
Also, you might ask why the `.cpp` and not the `.h` instead. Well, including the `.h` result in a compilation error with 4 unresolved external symbol...

```
0>Module.ElectronicNodes.cpp.obj: Error LNK2019 : symbole externe non r�solu "public: __cdecl FAnimGraphConnectionDrawingPolicy::FAnimGraphConnectionDrawingPolicy(int,int,float,class FSlateRect const &,class FSlateWindowElementList &,class UEdGraph *)" (??0FAnimGraphConnectionDrawingPolicy@@QEAA@HHMAEBVFSlateRect@@AEAVFSlateWindowElementList@@PEAVUEdGraph@@@Z) r�f�renc� dans la fonction "public: virtual class FConnectionDrawingPolicy * __cdecl FENConnectionDrawingPolicyFactory::CreateConnectionPolicy(class UEdGraphSchema const *,int,int,float,class FSlateRect const &,class FSlateWindowElementList &,class UEdGraph *)const " (?CreateConnectionPolicy@FENConnectionDrawingPolicyFactory@@UEBAPEAVFConnectionDrawingPolicy@@PEBVUEdGraphSchema@@HHMAEBVFSlateRect@@AEAVFSlateWindowElementList@@PEAVUEdGraph@@@Z)
0>Module.ElectronicNodes.cpp.obj: Error LNK2001 : symbole externe non r�solu "public: virtual bool __cdecl FAnimGraphConnectionDrawingPolicy::TreatWireAsExecutionPin(class UEdGraphPin *,class UEdGraphPin *)const " (?TreatWireAsExecutionPin@FAnimGraphConnectionDrawingPolicy@@UEBA_NPEAVUEdGraphPin@@0@Z)
0>Module.ElectronicNodes.cpp.obj: Error LNK2001 : symbole externe non r�solu "public: virtual void __cdecl FAnimGraphConnectionDrawingPolicy::BuildExecutionRoadmap(void)" (?BuildExecutionRoadmap@FAnimGraphConnectionDrawingPolicy@@UEAAXXZ)
0>Module.ElectronicNodes.cpp.obj: Error LNK2001 : symbole externe non r�solu "public: virtual void __cdecl FAnimGraphConnectionDrawingPolicy::DetermineStyleOfExecWire(float &,struct FLinearColor &,bool &,struct FKismetConnectionDrawingPolicy::FTimePair const &)" (?DetermineStyleOfExecWire@FAnimGraphConnectionDrawingPolicy@@UEAAXAEAMAEAUFLinearColor@@AEA_NAEBUFTimePair@FKismetConnectionDrawingPolicy@@@Z)
```

**Comment by GloryOfNight** [comment]
Hmm. Weird. I'll check it later.
There should be solution for this.

**Comment by TheHerobrine** [comment]
@GloryOfNight Out of curiosity, what is the problem with this include? If I can identify the problem, I could find a solution...

**Comment by GloryOfNight** [comment]
No compilation for plugin with editor without source files. 

Also, problems can occur when someone include 
`#include "ENAnimGraphConnectionDrawingPolicy.h"`
and `#include "AnimGraphConnectionDrawingPolicy.cpp"`
that one problem can be tricky to find what went wrong

And its just feel very wrong do such include. Hacks never a good solution, it can work at the time, but it will broke eventually. At least on my opinion.

**Comment by TheHerobrine** [comment]
Hum, you're right, I'm going to search for a better solution... (but no one should include `#include "ENAnimGraphConnectionDrawingPolicy.h"` since it's specific to Electronic Nodes)

**Comment by TheHerobrine** [comment]
Ok, I found a solution which require to copy the code of `AnimGraphConnectionDrawingPolicy.cpp` in the plugin folder.
And we will need those includes:
```
#include "Animation/AnimBlueprint.h"
#include "Animation/AnimBlueprintGeneratedClass.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "AnimationGraphSchema.h"
#include "AnimGraphNode_Base.h"
```

But no more `#include .cpp`! Would that be ok for you?

**Comment by GloryOfNight** [comment]
Are you coping files or the lines from code to code? 
If its lines, im 100% ok.

**Comment by TheHerobrine** [comment]
I'm copying the content of the file (so the lines) into my `ENAnimGraphConnectionDrawingPolicy.cpp` so that it can inherit directly from `FKismetConnectionDrawingPolicy` instead of `AnimGraphConnectionDrawingPolicy`.

Cool 🥳! I'll push this a bit later though, I sent Epic 3 versions already in the last week 😅...

**Comment by TheHerobrine** [comment]
It's being reviewed by the Unreal Marketplace team as of 2.9, and should be available in the next 24-48h 😉
