### ISSUE TITLE
Have to disable to push build

### ISSUE THREAD

**Issue by KhaosRaynes** [TheHerobrine/ElectronicNodes#3]
Remember to be specific and concise.
Loving your plugin but anytime I push my build to my team I have to disable it otherwise the individuals who do not have the plugin cannot load the project on 4.22.3

**Comment by TheHerobrine** [comment]
@KhaosRaynes Following [your comment ](https://forums.unrealengine.com/unreal-engine/marketplace/1647213-electronic-nodes-wiring-style-for-blueprint-and-material-editors?p=1668366#post1668366)on the forum, have you try to add the `.uproject` file on your `.gitignore`? (Or at least, not commiting the `.uproject` file).

This file is placed at the root of your project and you be named `[yourgame].uproject`

**Comment by TheHerobrine** [comment]
With no return from you, I close this issue as I think it was the `.uproject` file being shared ;)

You can of course comment this issue if it's not solved.
