### ISSUE TITLE
Add bubbles on wires connected to selected node

### ISSUE THREAD

**Issue by yholmes1** [TheHerobrine/ElectronicNodes#7]
**Describe the solution you'd like**
I would like to see the bubble lines only come from the selected node. Maybe node color can change once selected as well.

**Comment by TheHerobrine** [comment]
@yholmes1 I'm going to do it this week end.
Just to understand, you'd like to see:
- (1) bubbles on wires coming TO the node
- (2) bubbles on wires coming FROM the node
- (3) bubbles on wires coming TO **and** FROM the node

I think you mean (3), but it's just to be sure ;)

**Comment by yholmes1** [comment]
Yes number 3,
If this possible, only have the selected node be animated, and the none selected node bubbles should not move only when selected. hope that make sense.
    On Wednesday, October 30, 2019, 4:57:08 PM EDT, Hugo ATTAL <notifications@github.com> wrote:  
 
 
@yholmes1 I'm going to do it this week end.
Just to understand, you'd like to see:
   
   - (1) bubbles on wires coming TO the node
   - (2) bubbles on wires coming FROM the node
   - (3) bubbles on wires coming TO and FROM the node

I think you mean (3), but it's just to be sure ;)

**Comment by TheHerobrine** [comment]
@yholmes1 You have now several possibilities to display the bubbles!

![image](https://user-images.githubusercontent.com/4563971/68535182-81dfb980-033e-11ea-9ed4-76ba7c75a55a.png)

## Bubble Display Rule:
- **Always**: default
- **Display on selection**: the bubbles are display only when there is a selection
- **Move on selection**: the bubbles are always display, but onl  move when there is a selection

## Selection Rule:
- **Near**: only consider nodes that are close the one selected
![image](https://user-images.githubusercontent.com/4563971/68535158-054cdb00-033e-11ea-8401-ceec50f90fc0.png)

- **Far**: consider all the nodes that require or are required by this node
![image](https://user-images.githubusercontent.com/4563971/68535161-0d0c7f80-033e-11ea-839e-9e59a12f2486.png)

Of course, multi selection works as well (example with "near"):
![image](https://user-images.githubusercontent.com/4563971/68535172-578dfc00-033e-11ea-88c6-40ee81bc7ab7.png)

This feature should be available next week :)

**Comment by yholmes1** [comment]
This looks Fantastic,I  hope other users like this new update just as much as me.
    On Saturday, November 9, 2019, 4:18:31 PM EST, Hugo ATTAL <notifications@github.com> wrote:  
 
 
@yholmes1 You have now several possibilities to display the bubbles!



Bubble Display Rule:
   
   - Always: default
   - Display on selection: the bubbles are display only when there is a selection
   - Move on selection: the bubbles are always display, but onl move when there is a selection

Selection Rule:
   
   -    
Near: only consider nodes that are close the one selected   


   -    
Far: consider all the nodes that require or are required by this node   



Of course, multi selection works as well (example with "near"):


This feature should be available next week :)
